# Odejścia klientów w branży telekomunikacyjnej

### Opis kolumn

- **gender** – płeć klienta 
- **SeniorCitizen** – czy klient jest seniorem (1 – tak, 0 – nie) (1, 0)
- **Partner** – czy klient jest w związku / ma partnera (Yes, No)
- **Dependents** – czy klient posiada osoby na utrzymaniu (np. dzieci) (Yes, No)
- **tenure** – staż klienta; liczba miesięcy korzystania z usług firmy
- **PhoneService** – czy klient posiada aktywną usługę telefoniczną (Yes, No)
- **MultipleLines** – czy klient posiada wiele linii telefonicznych (Yes, No, No phone service)
- **InternetService** – rodzaj dostawcy usług internetowych klienta (DSL, Fiber optic, No)
- **OnlineSecurity** – czy klient ma wykupioną usługę bezpieczeństwa online (Yes, No, No internet service)
- **OnlineBackup** – czy klient posiada usługę kopii zapasowej w chmurze (Yes, No, No internet service)
- **DeviceProtection** – czy klient posiada dodatkowe ubezpieczenie/ochronę urządzenia (Yes, No, No internet service)
- **TechSupport** – czy klient korzysta z rozszerzonego wsparcia technicznego (Yes, No, No internet service)
- **StreamingTV** – czy klient posiada usługę streamingową TV (Yes, No, No internet service)
- **StreamingMovies** – czy klient posiada usługę streamingową filmów (Yes, No, No internet service)
- **Contract** – typ zawartej umowy (Month-to-month, One year, Two year)
- **PaperlessBilling** – czy klient otrzymuje faktury w formie elektronicznej (Yes, No)
- **PaymentMethod** – preferowana metoda płatności klienta (Electronic check, Mailed check, Bank transfer (automatic), Credit card (automatic))
- **MonthlyCharges** – wysokość aktualnej miesięcznej opłaty za usługi
- **TotalCharges** – całkowita suma opłat poniesionych przez klienta od początku umowy
- **Churn** – czy klient zrezygnował z usług (Yes or No)

In [118]:
import pandas as pd

df = pd.read_csv("data/telco_customer_churn.csv", index_col=0)
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
customerID,,,,,,,,,,,,,,,,,,,,
7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
print(df.shape)
df.info()

(7043, 20)
<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 7590-VHVEG to 3186-AJIEK
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   object
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   object
 3   Dependents        7043 non-null   object
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   object
 6   MultipleLines     7043 non-null   object
 7   InternetService   7043 non-null   object
 8   OnlineSecurity    7043 non-null   object
 9   OnlineBackup      7043 non-null   object
 10  DeviceProtection  7043 non-null   object
 11  TechSupport       7043 non-null   object
 12  StreamingTV       7043 non-null   object
 13  StreamingMovies   7043 non-null   object
 14  Contract          7043 non-null   object
 15  PaperlessBilling  7043 non-null   object
 16  PaymentMethod     7043 non-null   object
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7043 non-null   object
 19  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(17)
memory usage: 1.1+ MB

Zamiana nazw kolumn na `snake_case`

In [120]:
df = df.rename(columns={
    'SeniorCitizen': 'senior_citizen',
    'PhoneService': 'phone_service',
    'MultipleLines': 'multiple_lines',
    'InternetService': 'internet_service',
    'OnlineSecurity': 'online_security',
    'OnlineBackup': 'online_backup',
    'DeviceProtection': 'device_protection',
    'TechSupport': 'tech_support',
    'StreamingTV': 'streaming_tv',
    'StreamingMovies': 'streaming_movies',
    'PaperlessBilling': 'paperless_billing',
    'PaymentMethod': 'payment_method',
    'MonthlyCharges': 'monthly_charges',
    'TotalCharges': 'total_charges'
})
df.columns = df.columns.str.lower()
df.columns

Index(['gender', 'senior_citizen', 'partner', 'dependents', 'tenure',
       'phone_service', 'multiple_lines', 'internet_service',
       'online_security', 'online_backup', 'device_protection', 'tech_support',
       'streaming_tv', 'streaming_movies', 'contract', 'paperless_billing',
       'payment_method', 'monthly_charges', 'total_charges', 'churn'],
      dtype='object')

In [121]:
df['gender'] = df['gender'].map({'Male': 1, 'Female': 0})
df['gender']

customerID
7590-VHVEG    0
5575-GNVDE    1
3668-QPYBK    1
7795-CFOCW    1
9237-HQITU    0
             ..
6840-RESVB    1
2234-XADUH    0
4801-JZAZL    0
8361-LTMKD    1
3186-AJIEK    1
Name: gender, Length: 7043, dtype: int64

In [122]:
df['senior_citizen']

customerID
7590-VHVEG    0
5575-GNVDE    0
3668-QPYBK    0
7795-CFOCW    0
9237-HQITU    0
             ..
6840-RESVB    0
2234-XADUH    0
4801-JZAZL    0
8361-LTMKD    1
3186-AJIEK    0
Name: senior_citizen, Length: 7043, dtype: int64

In [123]:
df["partner"] = df['partner'].map({'Yes': 1, 'No': 0})
df["partner"]

customerID
7590-VHVEG    1
5575-GNVDE    0
3668-QPYBK    0
7795-CFOCW    0
9237-HQITU    0
             ..
6840-RESVB    1
2234-XADUH    1
4801-JZAZL    1
8361-LTMKD    1
3186-AJIEK    0
Name: partner, Length: 7043, dtype: int64

In [124]:
df["dependents"] = df['dependents'].map({'Yes': 1, 'No': 0})
df["dependents"]

customerID
7590-VHVEG    0
5575-GNVDE    0
3668-QPYBK    0
7795-CFOCW    0
9237-HQITU    0
             ..
6840-RESVB    1
2234-XADUH    1
4801-JZAZL    1
8361-LTMKD    0
3186-AJIEK    0
Name: dependents, Length: 7043, dtype: int64

In [125]:
df["tenure"]

customerID
7590-VHVEG     1
5575-GNVDE    34
3668-QPYBK     2
7795-CFOCW    45
9237-HQITU     2
              ..
6840-RESVB    24
2234-XADUH    72
4801-JZAZL    11
8361-LTMKD     4
3186-AJIEK    66
Name: tenure, Length: 7043, dtype: int64

In [126]:
df["phone_service"] = df["phone_service"].map({"Yes": 1, "No": 0})
df["phone_service"]

customerID
7590-VHVEG    0
5575-GNVDE    1
3668-QPYBK    1
7795-CFOCW    0
9237-HQITU    1
             ..
6840-RESVB    1
2234-XADUH    1
4801-JZAZL    0
8361-LTMKD    1
3186-AJIEK    1
Name: phone_service, Length: 7043, dtype: int64

In [127]:
cols_to_fix = [
    'multiple_lines', 'online_security', 'online_backup', 
    'device_protection', 'tech_support', 'streaming_tv', 'streaming_movies'
]

for col in cols_to_fix:
    df[col] = df[col].replace({'No internet service': 'No', 'No phone service': 'No'})
    df[col] = df[col].map({'Yes': 1, 'No': 0})

df[['multiple_lines', 'online_security', 'online_backup', 'device_protection', 'tech_support', 'streaming_tv', 'streaming_movies']]

,multiple_lines,online_security,online_backup,device_protection,tech_support,streaming_tv,streaming_movies
customerID,,,,,,,
7590-VHVEG,0,0,1,0,0,0,0
5575-GNVDE,0,1,0,1,0,0,0
3668-QPYBK,0,1,1,0,0,0,0
7795-CFOCW,0,1,0,1,1,0,0
9237-HQITU,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...
6840-RESVB,1,1,0,1,1,1,1
2234-XADUH,1,0,1,1,0,1,1
4801-JZAZL,0,1,0,0,0,0,0
8361-LTMKD,1,0,0,0,0,0,0
3186-AJIEK,0,1,0,1,1,1,1

In [128]:
df = pd.get_dummies(df, columns=['internet_service'], dtype=int)
df = df.rename(columns={
    'internet_service_DSL': 'internet_service_dsl',
    'internet_service_Fiber optic': 'internet_service_fiber_optic',
    'internet_service_No': 'internet_service_no' 
})
df[['internet_service_dsl', 'internet_service_fiber_optic', 'internet_service_no']]

,internet_service_dsl,internet_service_fiber_optic,internet_service_no
customerID,,,
7590-VHVEG,1,0,0
5575-GNVDE,1,0,0
3668-QPYBK,1,0,0
7795-CFOCW,1,0,0
9237-HQITU,0,1,0
...,...,...,...
6840-RESVB,1,0,0
2234-XADUH,0,1,0
4801-JZAZL,1,0,0
8361-LTMKD,0,1,0
3186-AJIEK,0,1,0

In [129]:
df = pd.get_dummies(df, columns=['contract'], dtype=int)
df = df.rename(columns={
    'contract_Month-to-month': 'contract_month_to_month',
    'contract_One year': 'contract_one_year',
    'contract_Two year': 'contract_two_year' 
})
df[['contract_month_to_month', 'contract_one_year', 'contract_two_year']]

            contract_month_to_month  contract_one_year  contract_two_year
customerID
7590-VHVEG                        1                  0                  0
5575-GNVDE                        0                  1                  0
3668-QPYBK                        1                  0                  0
7795-CFOCW                        0                  1                  0
9237-HQITU                        1                  0                  0
...                             ...                ...                ...
6840-RESVB                        0                  1                  0
2234-XADUH                        0                  1                  0
4801-JZAZL                        1                  0                  0
8361-LTMKD                        1                  0                  0
3186-AJIEK                        0                  0                  1

[7043 rows x 3 columns]

In [130]:
df["paperless_billing"] = df["paperless_billing"].map({"Yes": 1, "No": 0})
df["paperless_billing"]

customerID
7590-VHVEG    1
5575-GNVDE    0
3668-QPYBK    1
7795-CFOCW    0
9237-HQITU    1
             ..
6840-RESVB    1
2234-XADUH    1
4801-JZAZL    1
8361-LTMKD    1
3186-AJIEK    1
Name: paperless_billing, Length: 7043, dtype: int64

In [131]:
df["payment_method"].unique()

array(['Electronic check', 'Mailed check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

In [132]:
df = pd.get_dummies(df, columns=['payment_method'], dtype=int)
df = df.rename(columns={
    'payment_method_Bank transfer (automatic)': 'payment_method_bank_transfer_automatic',
    'payment_method_Credit card (automatic)': 'payment_method_credit_card_automatic',
    'payment_method_Electronic check': 'payment_method_electronic_check',
    'payment_method_Mailed check': 'payment_method_mailed_check'
})
df[['payment_method_bank_transfer_automatic', 'payment_method_credit_card_automatic', 
    'payment_method_electronic_check', 'payment_method_mailed_check']]

,payment_method_bank_transfer_automatic,payment_method_credit_card_automatic,payment_method_electronic_check,payment_method_mailed_check
customerID,,,,
7590-VHVEG,0,0,1,0
5575-GNVDE,0,0,0,1
3668-QPYBK,0,0,0,1
7795-CFOCW,1,0,0,0
9237-HQITU,0,0,1,0
...,...,...,...,...
6840-RESVB,0,0,0,1
2234-XADUH,0,1,0,0
4801-JZAZL,0,0,1,0
8361-LTMKD,0,0,0,1
3186-AJIEK,1,0,0,0

In [133]:
df["monthly_charges"]

customerID
7590-VHVEG     29.85
5575-GNVDE     56.95
3668-QPYBK     53.85
7795-CFOCW     42.30
9237-HQITU     70.70
               ...
6840-RESVB     84.80
2234-XADUH    103.20
4801-JZAZL     29.60
8361-LTMKD     74.40
3186-AJIEK    105.65
Name: monthly_charges, Length: 7043, dtype: float64

In [134]:
df['total_charges'] = pd.to_numeric(df['total_charges'], errors='coerce')
df['total_charges']

customerID
7590-VHVEG      29.85
5575-GNVDE    1889.50
3668-QPYBK     108.15
7795-CFOCW    1840.75
9237-HQITU     151.65
               ...
6840-RESVB    1990.50
2234-XADUH    7362.90
4801-JZAZL     346.45
8361-LTMKD     306.60
3186-AJIEK    6844.50
Name: total_charges, Length: 7043, dtype: float64

In [135]:
df["churn"] = df["churn"].map({"Yes": 1, "No": 0})
df["churn"]

customerID
7590-VHVEG    0
5575-GNVDE    0
3668-QPYBK    1
7795-CFOCW    0
9237-HQITU    1
             ..
6840-RESVB    0
2234-XADUH    0
4801-JZAZL    0
8361-LTMKD    1
3186-AJIEK    0
Name: churn, Length: 7043, dtype: int64

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 7590-VHVEG to 3186-AJIEK
Data columns (total 27 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   gender                                  7043 non-null   int64
 1   senior_citizen                          7043 non-null   int64
 2   partner                                 7043 non-null   int64
 3   dependents                              7043 non-null   int64
 4   tenure                                  7043 non-null   int64
 5   phone_service                           7043 non-null   int64
 6   multiple_lines                          7043 non-null   int64
 7   online_security                         7043 non-null   int64
 8   online_backup                           7043 non-null   int64
 9   device_protection                       7043 non-null   int64
 10  tech_support                            7043 non-null   int64
 11  streaming_tv                            7043 non-null   int64
 12  streaming_movies                        7043 non-null   int64
 13  paperless_billing                       7043 non-null   int64
 14  monthly_charges                         7043 non-null   float64
 15  total_charges                           7032 non-null   float64
 16  churn                                   7043 non-null   int64
 17  internet_service_dsl                    7043 non-null   int64
 18  internet_service_fiber_optic            7043 non-null   int64
 19  internet_service_no                     7043 non-null   int64
 20  contract_month_to_month                 7043 non-null   int64
 21  contract_one_year                       7043 non-null   int64
 22  contract_two_year                       7043 non-null   int64
 23  payment_method_bank_transfer_automatic  7043 non-null   int64
 24  payment_method_credit_card_automatic    7043 non-null   int64
 25  payment_method_electronic_check         7043 non-null   int64
 26  payment_method_mailed_check             7043 non-null   int64
dtypes: float64(2), int64(25)
memory usage: 1.8+ MB

In [137]:
df.isna().sum()

gender                                     0
senior_citizen                             0
partner                                    0
dependents                                 0
tenure                                     0
phone_service                              0
multiple_lines                             0
online_security                            0
online_backup                              0
device_protection                          0
tech_support                               0
streaming_tv                               0
streaming_movies                           0
paperless_billing                          0
monthly_charges                            0
total_charges                             11
churn                                      0
internet_service_dsl                       0
internet_service_fiber_optic               0
internet_service_no                        0
contract_month_to_month                    0
contract_one_year                          0
contract_two_year                          0
payment_method_bank_transfer_automatic     0
payment_method_credit_card_automatic       0
payment_method_electronic_check            0
payment_method_mailed_check                0
dtype: int64

In [138]:
temp_total_charges = pd.to_numeric(df['total_charges'], errors='coerce')
print(df[temp_total_charges.isna()][['tenure', 'total_charges']])

            tenure  total_charges
customerID
4472-LVYGI       0            NaN
3115-CZMZD       0            NaN
5709-LVOEQ       0            NaN
4367-NUYAO       0            NaN
1371-DWPAZ       0            NaN
7644-OMVMY       0            NaN
3213-VVOLG       0            NaN
2520-SGTTA       0            NaN
2923-ARZLG       0            NaN
4075-WKNIU       0            NaN
2775-SEFEE       0            NaN

In [139]:
df['total_charges'] = df['total_charges'].fillna(0)
df.isna().sum()

gender                                    0
senior_citizen                            0
partner                                   0
dependents                                0
tenure                                    0
phone_service                             0
multiple_lines                            0
online_security                           0
online_backup                             0
device_protection                         0
tech_support                              0
streaming_tv                              0
streaming_movies                          0
paperless_billing                         0
monthly_charges                           0
total_charges                             0
churn                                     0
internet_service_dsl                      0
internet_service_fiber_optic              0
internet_service_no                       0
contract_month_to_month                   0
contract_one_year                         0
contract_two_year                         0
payment_method_bank_transfer_automatic    0
payment_method_credit_card_automatic      0
payment_method_electronic_check           0
payment_method_mailed_check               0
dtype: int64

In [140]:
cols = [c for c in df.columns if c != 'churn'] + ['churn']
df = df[cols]

In [141]:
df.to_csv('data/preprocessed_telco_customer_churn.csv', index=True)

### Zaktualizowany opis kolumn

- **gender** – płeć klienta (1: Male, 0: Female).
- **senior_citizen** – czy klient ma 65+ lat (1, 0).
- **partner** – czy klient posiada partnera (1: Yes, 0: No).
- **dependents** – czy klient posiada osoby na utrzymaniu (1: Yes, 0: No).
- **tenure** – liczba miesięcy, przez które klient pozostał w firmie.
- **phone_service** – czy klient posiada usługę telefoniczną (1: Yes, 0: No).
- **multiple_lines** – czy klient posiada wiele linii (1: Yes, 0: No/No phone service).
- **online_security** – czy klient posiada zabezpieczenia online (1: Yes, 0: No/No internet service).
- **online_backup** – czy klient posiada kopię zapasową online (1: Yes, 0: No/No internet service).
- **device_protection** – czy klient posiada ochronę urządzenia (1: Yes, 0: No/No internet service).
- **tech_support** – czy klient posiada wsparcie techniczne (1: Yes, 0: No/No internet service).
- **streaming_tv** – czy klient posiada usługę streamingową TV (1: Yes, 0: No/No internet service).
- **streaming_movies** – czy klient posiada usługę streamingową filmów (1: Yes, 0: No/No internet service).
- **paperless_billing** – czy klient korzysta z fakturowania bezpapierowego (1: Yes, 0: No).
- **monthly_charges** – kwota, którą klient jest obciążany miesięcznie.
- **total_charges** – całkowita kwota, którą został obciążony klient (wartość numeryczna).
- **internet_service_dsl** – dostawca internetu to DSL (1: Yes, 0: No).
- **internet_service_fiber_optic** – dostawca internetu to światłowód (1: Yes, 0: No).
- **internet_service_no** – brak usługi internetowej (1: Yes, 0: No).
- **contract_month_to_month** – umowa miesięczna (1: Yes, 0: No).
- **contract_one_year** – umowa na rok (1: Yes, 0: No).
- **contract_two_year** – umowa na dwa lata (1: Yes, 0: No).
- **payment_method_bank_transfer_automatic** – płatność automatycznym przelewem bankowym (1: Yes, 0: No).
- **payment_method_credit_card_automatic** – płatność automatyczną kartą kredytową (1: Yes, 0: No).
- **payment_method_electronic_check** – płatność czekiem elektronicznym (1: Yes, 0: No).
- **payment_method_mailed_check** – płatność czekiem wysłanym pocztą (1: Yes, 0: No).
- **churn** – **Zmienna docelowa (target)**; czy klient odszedł (1: Yes, 0: No).